-- Auto-generated from src/data/mockData.ts. Safe to re-run (upserts).
-- Run this AFTER schema.sql, once, in the Supabase SQL Editor.

insert into public.hospitals (id, data) values
  ('hosp_st_francis', '{"id":"hosp_st_francis","name":"St. Francis Medical Center ED","systemName":"Prime Healthcare SoCal","address":"3630 E Imperial Hwy","city":"Lynwood","state":"CA","lat":33.9288,"lng":-118.204,"emrSystem":"Epic Systems","hospitalRating":4.8,"badge":"High Acuity ER","contactPerson":"Dr. Sarah Jenkins - EM Director","contactEmail":"moonlighting@stfrancis.org","logoUrl":"https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=150&auto=format&fit=crop&q=80"}'::jsonb),
  ('hosp_exer_sm', '{"id":"hosp_exer_sm","name":"Exer Urgent Care - Santa Monica","systemName":"Exer More Than Urgent Care Network","address":"2525 Wilshire Blvd","city":"Santa Monica","state":"CA","lat":34.0345,"lng":-118.4831,"emrSystem":"AthenaHealth","hospitalRating":4.9,"badge":"Urgent Care Fast-Track","contactPerson":"David Chen - Clinical Recruiter","contactEmail":"dchen@exerurgentcare.com"}'::jsonb),
  ('hosp_valley_pres', '{"id":"hosp_valley_pres","name":"Valley Presbyterian Community ED","systemName":"Valley Presbyterian Health System","address":"15107 Vanowen St","city":"Van Nuys","state":"CA","lat":34.1939,"lng":-118.4619,"emrSystem":"Cerner Millennium","hospitalRating":4.7,"badge":"Community ER","contactPerson":"Elena Rostova - Physician Recruiter","contactEmail":"elena.rostova@valleypres.org"}'::jsonb),
  ('hosp_kaiser_sunset', '{"id":"hosp_kaiser_sunset","name":"Kaiser Sunset Urgent Care Center","systemName":"Kaiser Permanente SoCal","address":"4867 Sunset Blvd","city":"Los Angeles","state":"CA","lat":34.1016,"lng":-118.2916,"emrSystem":"HealthConnect (Epic)","hospitalRating":4.8,"badge":"Same Day Pay","contactPerson":"Dr. Marcus Vance - Chief Medical Officer","contactEmail":"mvance@kp.org"}'::jsonb),
  ('hosp_glendale_adv', '{"id":"hosp_glendale_adv","name":"Glendale Adventist ER Division","systemName":"Adventist Health SoCal","address":"1509 Wilson Terrace","city":"Glendale","state":"CA","lat":34.1481,"lng":-118.2325,"emrSystem":"Epic Systems","hospitalRating":4.8,"contactPerson":"Rachel Adams - Medical Staff Services","contactEmail":"radams@ah.org"}'::jsonb),
  ('hosp_la_general', '{"id":"hosp_la_general","name":"LA General Medical Center (LAC+USC) ED","systemName":"LA County Dept of Health Services","address":"2051 Marengo St","city":"Los Angeles","state":"CA","lat":34.0578,"lng":-118.2048,"emrSystem":"ORCHID (Cerner)","hospitalRating":4.9,"badge":"Nocturnist Surge","contactPerson":"Tom Reynolds - EM Operations Lead","contactEmail":"treynolds@dhs.lacounty.gov"}'::jsonb),
  ('hosp_torrance_mem', '{"id":"hosp_torrance_mem","name":"Torrance Memorial Medical Center ED","systemName":"Cedars-Sinai Health System Affiliate","address":"3330 Lomita Blvd","city":"Torrance","state":"CA","lat":33.8058,"lng":-118.3533,"emrSystem":"Epic Systems","hospitalRating":4.9,"badge":"Level 2 Trauma","contactPerson":"Dr. Gregory Vance - EM Director","contactEmail":"gvance@tmmc.com"}'::jsonb)
on conflict (id) do update set data = excluded.data;

insert into public.shifts (id, data) values
  ('shift_101', '{"id":"shift_101","hospitalId":"hosp_st_francis","hospitalName":"St. Francis Medical Center ED","facilityLocation":"3630 E Imperial Hwy, Lynwood, CA","lat":33.9288,"lng":-118.204,"distanceMiles":8.5,"specialty":"Emergency Medicine","title":"High-Volume Community ER Nocturnist","department":"Emergency Department","hourlyRate":185,"totalPay":2220,"shiftType":"Night Shift","startTime":"19:00","endTime":"07:00","date":"2026-08-15","durationHours":12,"pgyRequirement":["PGY-2","PGY-3","PGY-4","Fellow"],"requiredDocIds":["pd_letter","state_license","dea_certificate","acls_card","malpractice_cert","tb_immunization"],"description":"Community ED nocturnist coverage in Level 2 Trauma center. ESI Level 2-4 management, rapid laceration repair, bedside ultrasound, and procedural sedation. Attending backup on site.","malpracticeIncluded":true,"restCallRoomAvailable":true,"mealStipend":true,"urgency":"High Demand","spotsAvailable":2}'::jsonb),
  ('shift_102', '{"id":"shift_102","hospitalId":"hosp_exer_sm","hospitalName":"Exer Urgent Care - Santa Monica","facilityLocation":"2525 Wilshire Blvd, Santa Monica, CA","lat":34.0345,"lng":-118.4831,"distanceMiles":4.2,"specialty":"Emergency Medicine","title":"Urgent Care Fast-Track Moonlighter","department":"Outpatient Urgent Care","hourlyRate":135,"totalPay":1080,"shiftType":"Day Shift","startTime":"09:00","endTime":"17:00","date":"2026-08-16","durationHours":8,"pgyRequirement":["PGY-2","PGY-3","PGY-4"],"requiredDocIds":["pd_letter","state_license","acls_card","malpractice_cert"],"description":"High-efficiency walk-in urgent care. Onsite digital X-Ray, splinting, CLIA-waived labs, and suture repairs. Average 20-24 walk-in patients per 8hr shift.","malpracticeIncluded":true,"restCallRoomAvailable":false,"mealStipend":true,"urgency":"Standard","spotsAvailable":1}'::jsonb),
  ('shift_103', '{"id":"shift_103","hospitalId":"hosp_valley_pres","hospitalName":"Valley Presbyterian Community ED","facilityLocation":"15107 Vanowen St, Van Nuys, CA","lat":34.1939,"lng":-118.4619,"distanceMiles":11.2,"specialty":"Emergency Medicine","title":"Community Emergency Department Swing Shift","department":"Emergency Department","hourlyRate":165,"totalPay":1650,"shiftType":"Swing Shift","startTime":"14:00","endTime":"00:00","date":"2026-08-15","durationHours":10,"pgyRequirement":["PGY-2","PGY-3","PGY-4","Fellow"],"requiredDocIds":["pd_letter","state_license","dea_certificate","acls_card","bls_card","malpractice_cert"],"description":"Peak volume swing coverage in 35-bed community ER. Manage abdominal pain, chest pain rule-outs, dyspnea, and simple orthopedics.","malpracticeIncluded":true,"restCallRoomAvailable":true,"mealStipend":true,"urgency":"Urgent","spotsAvailable":1}'::jsonb),
  ('shift_104', '{"id":"shift_104","hospitalId":"hosp_kaiser_sunset","hospitalName":"Kaiser Sunset Urgent Care Center","facilityLocation":"4867 Sunset Blvd, Los Angeles, CA","lat":34.1016,"lng":-118.2916,"distanceMiles":5,"specialty":"Emergency Medicine","title":"After-Hours Urgent Care Fast Track","department":"Outpatient Urgent Care","hourlyRate":145,"totalPay":1740,"shiftType":"Swing Shift","startTime":"12:00","endTime":"00:00","date":"2026-08-16","durationHours":12,"pgyRequirement":["PGY-2","PGY-3","PGY-4"],"requiredDocIds":["pd_letter","state_license","bls_card","malpractice_cert"],"description":"Dedicated urgent care fast track for Kaiser HealthConnect panel. Low acuity upper respiratory, cellulitis, sprains, and minor trauma.","malpracticeIncluded":true,"restCallRoomAvailable":false,"mealStipend":true,"urgency":"Urgent","spotsAvailable":3}'::jsonb),
  ('shift_105', '{"id":"shift_105","hospitalId":"hosp_glendale_adv","hospitalName":"Glendale Adventist ER Division","facilityLocation":"1509 Wilson Terrace, Glendale, CA","lat":34.1481,"lng":-118.2325,"distanceMiles":7.8,"specialty":"Emergency Medicine","title":"Community ER Overnight Attending Relief","department":"Emergency Department","hourlyRate":175,"totalPay":2100,"shiftType":"Night Shift","startTime":"20:00","endTime":"08:00","date":"2026-08-17","durationHours":12,"pgyRequirement":["PGY-2","PGY-3","PGY-4","Fellow"],"requiredDocIds":["pd_letter","state_license","dea_certificate","acls_card","malpractice_cert","tb_immunization","mask_fit"],"description":"Overnight ER coverage. High-volume chest pain protocols, acute strokes, and trauma stabilization. Double coverage with senior APP.","malpracticeIncluded":true,"restCallRoomAvailable":true,"mealStipend":true,"urgency":"High Demand","spotsAvailable":1}'::jsonb),
  ('shift_106', '{"id":"shift_106","hospitalId":"hosp_la_general","hospitalName":"LA General Medical Center (LAC+USC) ED","facilityLocation":"2051 Marengo St, Los Angeles, CA","lat":34.0578,"lng":-118.2048,"distanceMiles":5.4,"specialty":"Emergency Medicine","title":"Urgent ED Surge / High-Acuity Fast Track","department":"Department of Emergency Medicine","hourlyRate":205,"totalPay":2460,"shiftType":"Night Shift","startTime":"19:00","endTime":"07:00","date":"2026-08-22","durationHours":12,"pgyRequirement":["PGY-2","PGY-3","PGY-4","Fellow"],"requiredDocIds":["pd_letter","state_license","acls_card","bls_card","malpractice_cert"],"description":"Weekend surge coverage in urban Level 1 trauma ED. Acute resuscitation, procedural sedation, thoracostomies, and central line access.","malpracticeIncluded":true,"restCallRoomAvailable":true,"mealStipend":true,"urgency":"High Demand","spotsAvailable":1}'::jsonb),
  ('shift_107', '{"id":"shift_107","hospitalId":"hosp_torrance_mem","hospitalName":"Torrance Memorial Medical Center ED","facilityLocation":"3330 Lomita Blvd, Torrance, CA","lat":33.8058,"lng":-118.3533,"distanceMiles":14.1,"specialty":"Emergency Medicine","title":"Community ED Weekend Fast Track Relief","department":"Emergency Department","hourlyRate":155,"totalPay":1550,"shiftType":"Day Shift","startTime":"08:00","endTime":"18:00","date":"2026-08-23","durationHours":10,"pgyRequirement":["PGY-2","PGY-3","PGY-4"],"requiredDocIds":["pd_letter","state_license","dea_certificate","acls_card","malpractice_cert","tb_immunization"],"description":"Weekend fast track coverage at Torrance Memorial Level 2 Trauma center. Manage minor trauma, laceration repairs, splinting, and acute medical evaluations.","malpracticeIncluded":true,"restCallRoomAvailable":true,"mealStipend":true,"urgency":"Standard","spotsAvailable":2}'::jsonb)
on conflict (id) do update set data = excluded.data;

